<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0acb010a0a757365722e70726f746f1208736572766963657322190a0b55736572496e666f526571120a0a02496418012001280522350a0c55736572496e666f52657370120a0a024964180120012805120c0a044e616d65180220012809120b0a03536578180320012809324b0a0b5573657253657276696365123c0a0b67657455736572496e666f12152e73657276696365732e55736572496e666f5265711a162e73657276696365732e55736572496e666f52657370420c5a0a2e3b7365727669636573620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

